server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://192.168.1.224:3306/tao?useUnicode=true&characterEncoding=utf8&serverTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.transample
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mapper/mybatis-config.xml

