server:
  port: 8093
  servlet:
    session:
      timeout: 600

spring:
  datasource:
    url: jdbc:mysql://192.168.1.224:3306/kidmall?useUnicode=true&characterEncoding=utf8&serverTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

minio:
  endpoint: 192.168.1.224
  port: 9000
  accesskey: minioaccesskey
  secretKey: miniosecretkey
  secure: false
  bucketName: img


# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.transample
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mapper/mybatis-config.xml

